server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: drama
    password: drama
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: mappers/*_mapper.xml

pagehelper:
  helper-dialect: mysql

logging:
  level:
    com.drama.dao: debug




