server:
  port: 8080

datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://42.192.42.138:3306/drama?useUnicode=true&characterEncoding=utf8
  username: drama
  password: drama
  type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: mappers/*_mapper.xml




