server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.42.138:3306/drama?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: drama
    password: drama
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

mybatis:
  mapper-locations: mappers/*_mapper.xml

pagehelper:
  helper-dialect: mysql





